In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd

In [3]:
# data = pd.read_excel('path')
data = pd.read_excel('GFA_Dataset.xlsx')

In [5]:
X = data.drop('label', axis=1)
y_true = data['label']
X_train,X_test,y_train,y_test = train_test_split(X,y_true,test_size=0.10)

In [6]:
model = DecisionTreeClassifier()
params = model.get_params()
for param, value in params.items():
    print(f"{param}: {value}")

ccp_alpha: 0.0
class_weight: None
criterion: gini
max_depth: None
max_features: None
max_leaf_nodes: None
min_impurity_decrease: 0.0
min_samples_leaf: 1
min_samples_split: 2
min_weight_fraction_leaf: 0.0
random_state: None
splitter: best


In [8]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, cross_val_predict, KFold
kf = KFold(n_splits=10, shuffle=True)
confusion_matrices = []
classification_reports = []

In [9]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y_true.iloc[train_index], y_true.iloc[test_index]

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)
    cr = classification_report(y_test, y_pred)

    confusion_matrices.append(cm)
    classification_reports.append(cr)

In [10]:
for i, (cm, cr) in enumerate(zip(confusion_matrices, classification_reports)):
    print(f"Fold {i+1}:")
    print("Confusion Matrix:")
    print(cm)
    print("Classification Report:")
    print(cr)
    print("-" * 50)

Fold 1:
Confusion Matrix:
[[ 70  31]
 [ 29 566]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.69      0.70       101
           1       0.95      0.95      0.95       595

    accuracy                           0.91       696
   macro avg       0.83      0.82      0.82       696
weighted avg       0.91      0.91      0.91       696

--------------------------------------------------
Fold 2:
Confusion Matrix:
[[ 79  35]
 [ 35 547]]
Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.69      0.69       114
           1       0.94      0.94      0.94       582

    accuracy                           0.90       696
   macro avg       0.82      0.82      0.82       696
weighted avg       0.90      0.90      0.90       696

--------------------------------------------------
Fold 3:
Confusion Matrix:
[[ 73  30]
 [ 35 558]]
Classification Report:
              precision    r

In [11]:
import numpy as np
average_cm = np.mean(confusion_matrices, axis=0)
y_pred_all = cross_val_predict(model, X, y_true)
average_cr = classification_report(y_true, y_pred_all)
print("Average Confusion Matrix:")
print(average_cm)
print('Accary:', (cm[1,1]+cm[0,0])/(cm[1,1]+cm[0,1]+cm[0,0]+cm[1,0]))

Average Confusion Matrix:
[[ 74.8  30.2]
 [ 30.4 560.3]]
Accary: 0.9107913669064748
