In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

In [4]:
model = RandomForestClassifier(n_estimators=100,max_depth=4, max_features=0.4)
params = model.get_params()
for param, value in params.items():
    print(f"{param}: {value}")

bootstrap: True
ccp_alpha: 0.0
class_weight: None
criterion: gini
max_depth: 4
max_features: 0.4
max_leaf_nodes: None
max_samples: None
min_impurity_decrease: 0.0
min_samples_leaf: 1
min_samples_split: 2
min_weight_fraction_leaf: 0.0
n_estimators: 100
n_jobs: None
oob_score: False
random_state: None
verbose: 0
warm_start: False


In [5]:
import pandas as pd

In [6]:
# data = pd.read_excel('path')
data = pd.read_excel('GFA_Dataset.xlsx')

In [7]:
X = data.drop('label', axis=1)
y_true = data['label']
X_train,X_test,y_train,y_test = train_test_split(X,y_true,test_size=0.10)

In [8]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, cross_val_predict, KFold
kf = KFold(n_splits=10, shuffle=True)
confusion_matrices = []
classification_reports = []

In [9]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y_true.iloc[train_index], y_true.iloc[test_index]

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)
    cr = classification_report(y_test, y_pred)

    confusion_matrices.append(cm)
    classification_reports.append(cr)

In [10]:
for i, (cm, cr) in enumerate(zip(confusion_matrices, classification_reports)):
    print(f"Fold {i+1}:")
    print("Confusion Matrix:")
    print(cm)
    print("Classification Report:")
    print(cr)
    print("-" * 50)

Fold 1:
Confusion Matrix:
[[  8  99]
 [  4 585]]
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.07      0.13       107
           1       0.86      0.99      0.92       589

    accuracy                           0.85       696
   macro avg       0.76      0.53      0.53       696
weighted avg       0.83      0.85      0.80       696

--------------------------------------------------
Fold 2:
Confusion Matrix:
[[ 16  89]
 [  0 591]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.15      0.26       105
           1       0.87      1.00      0.93       591

    accuracy                           0.87       696
   macro avg       0.93      0.58      0.60       696
weighted avg       0.89      0.87      0.83       696

--------------------------------------------------
Fold 3:
Confusion Matrix:
[[ 12 114]
 [  1 569]]
Classification Report:
              precision    r

In [11]:
import numpy as np
average_cm = np.mean(confusion_matrices, axis=0)
y_pred_all = cross_val_predict(model, X, y_true)
average_cr = classification_report(y_true, y_pred_all)
print("Average Confusion Matrix:")
print(average_cm)
print('Accary:', (cm[1,1]+cm[0,0])/(cm[1,1]+cm[0,1]+cm[0,0]+cm[1,0]))

Average Confusion Matrix:
[[ 10.5  94.5]
 [  0.8 589.9]]
Accary: 0.8431654676258993
