In [1]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd

In [3]:
# data = pd.read_excel('path')
data = pd.read_excel('GFA_Dataset.xlsx')

In [4]:
X = data.drop('label', axis=1)
y_true = data['label']
X_train,X_test,y_train,y_test = train_test_split(X,y_true,test_size=0.10)

In [5]:
model = SVC()
params = model.get_params()
for param, value in params.items():
    print(f"{param}: {value}")

C: 1.0
break_ties: False
cache_size: 200
class_weight: None
coef0: 0.0
decision_function_shape: ovr
degree: 3
gamma: scale
kernel: rbf
max_iter: -1
probability: False
random_state: None
shrinking: True
tol: 0.001
verbose: False


In [6]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, cross_val_predict, KFold
kf = KFold(n_splits=10, shuffle=True)
confusion_matrices = []
classification_reports = []

In [7]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y_true.iloc[train_index], y_true.iloc[test_index]

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)
    cr = classification_report(y_test, y_pred)

    confusion_matrices.append(cm)
    classification_reports.append(cr)

C:\Users\23395\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\23395\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\23395\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469

In [8]:
for i, (cm, cr) in enumerate(zip(confusion_matrices, classification_reports)):
    print(f"Fold {i+1}:")
    print("Confusion Matrix:")
    print(cm)
    print("Classification Report:")
    print(cr)
    print("-" * 50)

Fold 1:
Confusion Matrix:
[[  0 101]
 [  0 595]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       101
           1       0.85      1.00      0.92       595

    accuracy                           0.85       696
   macro avg       0.43      0.50      0.46       696
weighted avg       0.73      0.85      0.79       696

--------------------------------------------------
Fold 2:
Confusion Matrix:
[[  0 114]
 [  0 582]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       114
           1       0.84      1.00      0.91       582

    accuracy                           0.84       696
   macro avg       0.42      0.50      0.46       696
weighted avg       0.70      0.84      0.76       696

--------------------------------------------------
Fold 3:
Confusion Matrix:
[[  0 105]
 [  0 591]]
Classification Report:
              precision    r

In [9]:
import numpy as np
average_cm = np.mean(confusion_matrices, axis=0)
y_pred_all = cross_val_predict(model, X, y_true)
average_cr = classification_report(y_true, y_pred_all)
print("Average Confusion Matrix:")
print(average_cm)
print('Accary:', (cm[1,1]+cm[0,0])/(cm[1,1]+cm[0,1]+cm[0,0]+cm[1,0]))

Average Confusion Matrix:
[[  0.  105. ]
 [  0.  590.7]]
Accary: 0.8431654676258993


C:\Users\23395\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\23395\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\23395\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469